### PR TITLE
Build and project upgrades

### PR DESCRIPTION
**Pull request by lesserwhirls**
* Migrate to Gradle 7.5.1 and the Kotlin DSL
* Upgrade various dependencies to their latest version
  * apache commons-io: 2.4 -> 2.11.0
  * jackson-datatype: 2.9.6 -> 2.13.3
  * kotlin_coroutine: 1.0.1 -> 4.6.4
  * guava: (transitive) -> 31.1-jre
  * okhttp
    * logging-inteceptor: 3.11.0 -> 4.10.0
    * mockwebserver: 2.7.5 -> 4.10.0
  * retrofit: 2.4.0 -> 2.9.0
  * slf4j: 1.7.25 -> 1.7.36
* testing framework:
  * junit: 4.12 -> junit-jupiter 5.9.0
* Separate Java and Kotlin sources in API project 

The PR also updates the GitHub Action workflow to run tests using the three current LTS versions of the Java (8, 11, and 17).

### CODE REVIEW

**Comment by scribe** [comment]
You can tell me no, but  is the existing java auto-convertable to kotlin? If it is, do you think it'd be wise here?

**Comment by lesserwhirls** [comment]
I avoided making any code changes that were not necessary for the upgrades at this point, but there are some that will need to be made. For example, we need to migrate away from simple-xml to another framework (Retrofit recommends JAXB, but I'm not sure yet). In terms of moving everything to Kotlin, the heaviest lift would be https://github.com/SpectraLogic/tpfr_java_client/blob/master/api/src/main/java/com/spectralogic/tpfr/api/ServerServiceFactoryImpl.java, but it's doable (maybe not auto-convertable, but not sure). The others should not be an issue. Probably best for another PR though.

**Comment by lesserwhirls** [comment]
We also need to edit the branch protection settings to depend on the three JDK version tests, and not the old "build" test for GitHub Actions. I would do that, but I don't have access to the project settings like I did for the ds3_java_sdk repo.

**Comment by scribe** [comment]
@lesserwhirls You should have better access now.

**Comment by lesserwhirls** [comment]
> @lesserwhirls You should have better access now.

Sweet - that worked :-)

**Comment by lesserwhirls** [comment]
Does this one look ok @scribe?

**Review by scribe — APPROVED** [review]
Looks good to me.

**Pull request merged**
