### PR TITLE
Migrate from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by lesserwhirls**
In the process of migrating to GitHub actions for testing, I also cleaned up how line endings for certain files are handled by git. Specifically, .bat and .ps1 files should always use CRLF. Also, when running the client tests on a windows machine, the line endings in the file `client/src/test/resources/xml/test.xml` must be "LF", otherwise the test will fail.

This work is motivated by [ESCP-3309](https://jira.spectralogic.com/browse/ESCP-3309), just in case there are code changes that need to be made in this repo.

### CODE REVIEW

**Review by david-limbach — APPROVED** [review]
LGTM

**Comment by shabtaisharon** [comment]
@david-limbach @lesserwhirls please take into consideration that Github action is not completely free, Spectra organization gets 2,000 Minutes (per month) so if you move all the SDKs to use Github action you might run out of minutes, just an FYI :)

**Comment by lesserwhirls** [comment]
Thanks for the heads up @shabtaisharon! Since this is a public repo, it should not have a limitation on the aggerate amount of monthly runtime and is only restricted by the [general usage limitations](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits). Each private repo should get [2000 minutes](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes) for free though. Given the amount of private repositories Spectra has, I'm guessing we have a paid plan of some sort, so it might be even higher that 2000 minutes for our private repos. I don't have access to the organization level details though, and I don't think I can see our current usage statistics to be 100% sure.

**Comment by shabtaisharon** [comment]
Cool, I gave @david-limbach access to the organization level before I left so he should be able to see all the details 😉

**Comment by david-limbach** [comment]
> Cool, I gave @david-limbach access to the organization level before I left so he should be able to see all the details 😉

Just downloaded an actions usage report, 1,876 of 3,000 minutes used with 9 days left in the billing cycle.  

Over the past few months the biggest usage of actions are:
- Escape_pod:  2,480
- Vail-test:  1,832
- Lumos:   1,066
- Lathe:    370

I will set a reminder to check this monthly to see if our recent additions put us too close to our limits.

Thanks @shabtaisharon

**Comment by shabtaisharon** [comment]
sure thing, I also bumped it a little (extra cost) when we did more work in Rio and Barry approved it. You might consider changing that so Spectra will not be overpaying what you think you should pay. ❤️

**Pull request merged**
